"""initial migration

Revision ID: 15b52fbcaf3b
Revises: 
Create Date: 2026-06-02 17:42:35.277385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15b52fbcaf3b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compound_cr_fifteen',
    sa.Column('compound_id', sa.String(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('compound_id'),
    schema='chemoproteomics'
    )
    op.create_table('compound_cr_four',
    sa.Column('compound_id', sa.String(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('compound_id'),
    schema='chemoproteomics'
    )
    op.create_table('residuelists',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    schema='chemoproteomics'
    )
    op.create_table('celltypes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('depmapid', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='core'
    )
    op.create_table('compounds',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('smiles', sa.String(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='core'
    )
    with op.batch_alter_table('compounds', schema='core') as batch_op:
        batch_op.create_index(batch_op.f('ix_core_compounds_image'), ['image'], unique=False)
        batch_op.create_index(batch_op.f('ix_core_compounds_smiles'), ['smiles'], unique=False)

    op.create_table('experiments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='core'
    )
    op.create_table('proteins',
    sa.Column('uniprot', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('symbol', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('uniprot'),
    schema='core'
    )
    with op.batch_alter_table('proteins', schema='core') as batch_op:
        batch_op.create_index(batch_op.f('ix_core_proteins_symbol'), ['symbol'], unique=False)

    op.create_table('structures',
    sa.Column('id', sa.String(length=10), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('resolution', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='structure'
    )
    op.create_table('residues',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('uniprot', sa.String(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['uniprot'], ['core.proteins.uniprot'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='chemoproteomics'
    )
    with op.batch_alter_table('residues', schema='chemoproteomics') as batch_op:
        batch_op.create_index(batch_op.f('ix_chemoproteomics_residues_type'), ['type'], unique=False)
        batch_op.create_index(batch_op.f('ix_chemoproteomics_residues_uniprot'), ['uniprot'], unique=False)

    op.create_table('plexs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('experiment_id', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['experiment_id'], ['core.experiments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='core'
    )
    op.create_table('proteinsynonyms',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('protein_id', sa.String(), nullable=True),
    sa.Column('synonym', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['protein_id'], ['core.proteins.uniprot'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='core'
    )
    op.create_table('ligands',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('structure_id', sa.String(), nullable=True),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('chain', sa.String(), nullable=True),
    sa.Column('smiles', sa.String(), nullable=True),
    sa.Column('inchi', sa.String(), nullable=True),
    sa.Column('chembl', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('mw', sa.Float(), nullable=True),
    sa.Column('artefact', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['structure_id'], ['structure.structures.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='structure'
    )
    with op.batch_alter_table('ligands', schema='structure') as batch_op:
        batch_op.create_index(batch_op.f('ix_structure_ligands_chain'), ['chain'], unique=False)
        batch_op.create_index(batch_op.f('ix_structure_ligands_chembl'), ['chembl'], unique=False)
        batch_op.create_index(batch_op.f('ix_structure_ligands_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_structure_ligands_inchi'), ['inchi'], unique=False)
        batch_op.create_index(batch_op.f('ix_structure_ligands_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_structure_ligands_smiles'), ['smiles'], unique=False)
        batch_op.create_index(batch_op.f('ix_structure_ligands_structure_id'), ['structure_id'], unique=False)

    op.create_table('pockets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('structure_id', sa.String(), nullable=True),
    sa.Column('pocket_id', sa.String(), nullable=True),
    sa.Column('pocket_score', sa.Float(), nullable=True),
    sa.Column('drug_score', sa.Float(), nullable=True),
    sa.Column('mean_confidence', sa.Float(), nullable=True),
    sa.Column('median_confidence', sa.Float(), nullable=True),
    sa.Column('min_confidence', sa.Float(), nullable=True),
    sa.Column('pocket_volume_MC', sa.Float(), nullable=True),
    sa.Column('pocket_volume_hull', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['structure_id'], ['structure.structures.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='structure'
    )
    with op.batch_alter_table('pockets', schema='structure') as batch_op:
        batch_op.create_index(batch_op.f('ix_structure_pockets_drug_score'), ['drug_score'], unique=False)
        batch_op.create_index(batch_op.f('ix_structure_pockets_pocket_score'), ['pocket_score'], unique=False)
        batch_op.create_index(batch_op.f('ix_structure_pockets_structure_id'), ['structure_id'], unique=False)

    op.create_table('structurechains',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('structure_id', sa.String(), nullable=True),
    sa.Column('chain', sa.UUID(), nullable=True),
    sa.Column('uniprot_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['chain'], ['structure.structurechains.id'], ),
    sa.ForeignKeyConstraint(['structure_id'], ['structure.structures.id'], ),
    sa.ForeignKeyConstraint(['uniprot_id'], ['core.proteins.uniprot'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='structure'
    )
    op.create_table('list2residue',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('residue_id', sa.UUID(), nullable=True),
    sa.Column('residuelist_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['residue_id'], ['chemoproteomics.residues.id'], ),
    sa.ForeignKeyConstraint(['residuelist_id'], ['chemoproteomics.residuelists.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    schema='chemoproteomics'
    )
    with op.batch_alter_table('list2residue', schema='chemoproteomics') as batch_op:
        batch_op.create_index(batch_op.f('ix_chemoproteomics_list2residue_residue_id'), ['residue_id'], unique=False)

    op.create_table('residuefeatures',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('residue_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['residue_id'], ['chemoproteomics.residues.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('residue_id', 'description', 'source'),
    schema='chemoproteomics'
    )
    with op.batch_alter_table('residuefeatures', schema='chemoproteomics') as batch_op:
        batch_op.create_index(batch_op.f('ix_chemoproteomics_residuefeatures_description'), ['description'], unique=False)
        batch_op.create_index(batch_op.f('ix_chemoproteomics_residuefeatures_residue_id'), ['residue_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chemoproteomics_residuefeatures_source'), ['source'], unique=False)

    op.create_table('compoundtreatments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('plex_id', sa.String(), nullable=False),
    sa.Column('samplename', sa.String(), nullable=False),
    sa.Column('compound_id', sa.String(), nullable=False),
    sa.Column('celltype_id', sa.UUID(), nullable=False),
    sa.Column('tmtchannel', sa.String(), nullable=True),
    sa.Column('concentration', sa.Float(), nullable=True),
    sa.Column('concentrationunits', sa.String(), nullable=True),
    sa.Column('time', sa.Float(), nullable=True),
    sa.Column('timeunits', sa.String(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('probe_id', sa.String(), nullable=True),
    sa.Column('probeconcentration', sa.Float(), nullable=True),
    sa.Column('probeconcentrationunits', sa.String(), nullable=True),
    sa.Column('probetime', sa.Float(), nullable=True),
    sa.Column('probetimeunits', sa.String(), nullable=True),
    sa.Column('comments', sa.String(), nullable=True),
    sa.Column('isreference', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['celltype_id'], ['core.celltypes.id'], ),
    sa.ForeignKeyConstraint(['compound_id'], ['core.compounds.id'], ),
    sa.ForeignKeyConstraint(['plex_id'], ['core.plexs.id'], ),
    sa.ForeignKeyConstraint(['probe_id'], ['core.compounds.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plex_id', 'samplename'),
    schema='core'
    )
    with op.batch_alter_table('compoundtreatments', schema='core') as batch_op:
        batch_op.create_index(batch_op.f('ix_core_compoundtreatments_compound_id'), ['compound_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_core_compoundtreatments_isreference'), ['isreference'], unique=False)
        batch_op.create_index(batch_op.f('ix_core_compoundtreatments_probe_id'), ['probe_id'], unique=False)

    op.create_table('structureresidues',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('structure_id', sa.String(), nullable=True),
    sa.Column('chain_id', sa.UUID(), nullable=True),
    sa.Column('residue_id', sa.UUID(), nullable=True),
    sa.Column('pdb_position', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('in_disulfide', sa.Boolean(), nullable=True),
    sa.Column('accessibility', sa.Float(), nullable=True),
    sa.Column('depth', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['chain_id'], ['structure.structurechains.id'], ),
    sa.ForeignKeyConstraint(['residue_id'], ['chemoproteomics.residues.id'], ),
    sa.ForeignKeyConstraint(['structure_id'], ['structure.structures.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='structure'
    )
    with op.batch_alter_table('structureresidues', schema='structure') as batch_op:
        batch_op.create_index(batch_op.f('ix_structure_structureresidues_accessibility'), ['accessibility'], unique=False)
        batch_op.create_index(batch_op.f('ix_structure_structureresidues_depth'), ['depth'], unique=False)
        batch_op.create_index(batch_op.f('ix_structure_structureresidues_in_disulfide'), ['in_disulfide'], unique=False)
        batch_op.create_index(batch_op.f('ix_structure_structureresidues_pdb_position'), ['pdb_position'], unique=False)

    op.create_table('competitionratios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('plex_id', sa.String(), nullable=True),
    sa.Column('compoundtreatment_id', sa.UUID(), nullable=True),
    sa.Column('residue_id', sa.UUID(), nullable=True),
    sa.Column('scan', sa.String(), nullable=True),
    sa.Column('cr', sa.Float(), nullable=True),
    sa.Column('control_rsd', sa.Float(), nullable=True),
    sa.Column('display_flag', sa.Boolean(), nullable=False),
    sa.Column('multimapper', sa.Boolean(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=True),
    sa.Column('group_cr', sa.Float(), nullable=True),
    sa.Column('p_value', sa.Float(), nullable=True),
    sa.Column('replicate_no', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['compoundtreatment_id'], ['core.compoundtreatments.id'], ),
    sa.ForeignKeyConstraint(['plex_id'], ['core.plexs.id'], ),
    sa.ForeignKeyConstraint(['residue_id'], ['chemoproteomics.residues.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='chemoproteomics'
    )
    with op.batch_alter_table('competitionratios', schema='chemoproteomics') as batch_op:
        batch_op.create_index(batch_op.f('ix_chemoproteomics_competitionratios_compoundtreatment_id'), ['compoundtreatment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chemoproteomics_competitionratios_control_rsd'), ['control_rsd'], unique=False)
        batch_op.create_index(batch_op.f('ix_chemoproteomics_competitionratios_group_cr'), ['group_cr'], unique=False)
        batch_op.create_index(batch_op.f('ix_chemoproteomics_competitionratios_p_value'), ['p_value'], unique=False)
        batch_op.create_index(batch_op.f('ix_chemoproteomics_competitionratios_plex_id'), ['plex_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chemoproteomics_competitionratios_replicate_no'), ['replicate_no'], unique=False)
        batch_op.create_index(batch_op.f('ix_chemoproteomics_competitionratios_residue_id'), ['residue_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chemoproteomics_competitionratios_scan'), ['scan'], unique=False)

    op.create_table('intensityreadings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('plex_id', sa.String(), nullable=True),
    sa.Column('compoundtreatment_id', sa.UUID(), nullable=True),
    sa.Column('residue_id', sa.UUID(), nullable=True),
    sa.Column('scan', sa.String(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('peptideseq', sa.String(), nullable=True),
    sa.Column('modification', sa.String(), nullable=True),
    sa.Column('multimapper', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['compoundtreatment_id'], ['core.compoundtreatments.id'], ),
    sa.ForeignKeyConstraint(['plex_id'], ['core.plexs.id'], ),
    sa.ForeignKeyConstraint(['residue_id'], ['chemoproteomics.residues.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='chemoproteomics'
    )
    with op.batch_alter_table('intensityreadings', schema='chemoproteomics') as batch_op:
        batch_op.create_index(batch_op.f('ix_chemoproteomics_intensityreadings_compoundtreatment_id'), ['compoundtreatment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chemoproteomics_intensityreadings_plex_id'), ['plex_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chemoproteomics_intensityreadings_residue_id'), ['residue_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chemoproteomics_intensityreadings_scan'), ['scan'], unique=False)

    op.create_table('foldchanges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('plex_id', sa.String(), nullable=True),
    sa.Column('compoundtreatment_id', sa.UUID(), nullable=True),
    sa.Column('protein_id', sa.String(), nullable=True),
    sa.Column('scan', sa.String(), nullable=True),
    sa.Column('foldchange', sa.Float(), nullable=True),
    sa.Column('p_value', sa.Float(), nullable=True),
    sa.Column('replicate_no', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['compoundtreatment_id'], ['core.compoundtreatments.id'], ),
    sa.ForeignKeyConstraint(['plex_id'], ['core.plexs.id'], ),
    sa.ForeignKeyConstraint(['protein_id'], ['core.proteins.uniprot'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='proteomics'
    )
    with op.batch_alter_table('foldchanges', schema='proteomics') as batch_op:
        batch_op.create_index(batch_op.f('ix_proteomics_foldchanges_compoundtreatment_id'), ['compoundtreatment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_proteomics_foldchanges_plex_id'), ['plex_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_proteomics_foldchanges_protein_id'), ['protein_id'], unique=False)

    op.create_table('protein_intensityreadings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('plex_id', sa.String(), nullable=True),
    sa.Column('compoundtreatment_id', sa.UUID(), nullable=True),
    sa.Column('protein_id', sa.String(), nullable=True),
    sa.Column('scan', sa.String(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['compoundtreatment_id'], ['core.compoundtreatments.id'], ),
    sa.ForeignKeyConstraint(['plex_id'], ['core.plexs.id'], ),
    sa.ForeignKeyConstraint(['protein_id'], ['core.proteins.uniprot'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='proteomics'
    )
    with op.batch_alter_table('protein_intensityreadings', schema='proteomics') as batch_op:
        batch_op.create_index(batch_op.f('ix_proteomics_protein_intensityreadings_compoundtreatment_id'), ['compoundtreatment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_proteomics_protein_intensityreadings_plex_id'), ['plex_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_proteomics_protein_intensityreadings_protein_id'), ['protein_id'], unique=False)

    op.create_table('ligand_residue_distances',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ligand_id', sa.UUID(), nullable=True),
    sa.Column('structureresidue_id', sa.UUID(), nullable=True),
    sa.Column('distance', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['ligand_id'], ['structure.ligands.id'], ),
    sa.ForeignKeyConstraint(['structureresidue_id'], ['structure.structureresidues.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ligand_id', 'structureresidue_id'),
    schema='structure'
    )
    with op.batch_alter_table('ligand_residue_distances', schema='structure') as batch_op:
        batch_op.create_index(batch_op.f('ix_structure_ligand_residue_distances_distance'), ['distance'], unique=False)

    op.create_table('pocket_residues',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pocket_id', sa.UUID(), nullable=True),
    sa.Column('structureresidue_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['pocket_id'], ['structure.pockets.id'], ),
    sa.ForeignKeyConstraint(['structureresidue_id'], ['structure.structureresidues.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='structure'
    )
    with op.batch_alter_table('pocket_residues', schema='structure') as batch_op:
        batch_op.create_index(batch_op.f('ix_structure_pocket_residues_pocket_id'), ['pocket_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_structure_pocket_residues_structureresidue_id'), ['structureresidue_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pocket_residues', schema='structure') as batch_op:
        batch_op.drop_index(batch_op.f('ix_structure_pocket_residues_structureresidue_id'))
        batch_op.drop_index(batch_op.f('ix_structure_pocket_residues_pocket_id'))

    op.drop_table('pocket_residues', schema='structure')
    with op.batch_alter_table('ligand_residue_distances', schema='structure') as batch_op:
        batch_op.drop_index(batch_op.f('ix_structure_ligand_residue_distances_distance'))

    op.drop_table('ligand_residue_distances', schema='structure')
    with op.batch_alter_table('protein_intensityreadings', schema='proteomics') as batch_op:
        batch_op.drop_index(batch_op.f('ix_proteomics_protein_intensityreadings_protein_id'))
        batch_op.drop_index(batch_op.f('ix_proteomics_protein_intensityreadings_plex_id'))
        batch_op.drop_index(batch_op.f('ix_proteomics_protein_intensityreadings_compoundtreatment_id'))

    op.drop_table('protein_intensityreadings', schema='proteomics')
    with op.batch_alter_table('foldchanges', schema='proteomics') as batch_op:
        batch_op.drop_index(batch_op.f('ix_proteomics_foldchanges_protein_id'))
        batch_op.drop_index(batch_op.f('ix_proteomics_foldchanges_plex_id'))
        batch_op.drop_index(batch_op.f('ix_proteomics_foldchanges_compoundtreatment_id'))

    op.drop_table('foldchanges', schema='proteomics')
    with op.batch_alter_table('intensityreadings', schema='chemoproteomics') as batch_op:
        batch_op.drop_index(batch_op.f('ix_chemoproteomics_intensityreadings_scan'))
        batch_op.drop_index(batch_op.f('ix_chemoproteomics_intensityreadings_residue_id'))
        batch_op.drop_index(batch_op.f('ix_chemoproteomics_intensityreadings_plex_id'))
        batch_op.drop_index(batch_op.f('ix_chemoproteomics_intensityreadings_compoundtreatment_id'))

    op.drop_table('intensityreadings', schema='chemoproteomics')
    with op.batch_alter_table('competitionratios', schema='chemoproteomics') as batch_op:
        batch_op.drop_index(batch_op.f('ix_chemoproteomics_competitionratios_scan'))
        batch_op.drop_index(batch_op.f('ix_chemoproteomics_competitionratios_residue_id'))
        batch_op.drop_index(batch_op.f('ix_chemoproteomics_competitionratios_replicate_no'))
        batch_op.drop_index(batch_op.f('ix_chemoproteomics_competitionratios_plex_id'))
        batch_op.drop_index(batch_op.f('ix_chemoproteomics_competitionratios_p_value'))
        batch_op.drop_index(batch_op.f('ix_chemoproteomics_competitionratios_group_cr'))
        batch_op.drop_index(batch_op.f('ix_chemoproteomics_competitionratios_control_rsd'))
        batch_op.drop_index(batch_op.f('ix_chemoproteomics_competitionratios_compoundtreatment_id'))

    op.drop_table('competitionratios', schema='chemoproteomics')
    with op.batch_alter_table('structureresidues', schema='structure') as batch_op:
        batch_op.drop_index(batch_op.f('ix_structure_structureresidues_pdb_position'))
        batch_op.drop_index(batch_op.f('ix_structure_structureresidues_in_disulfide'))
        batch_op.drop_index(batch_op.f('ix_structure_structureresidues_depth'))
        batch_op.drop_index(batch_op.f('ix_structure_structureresidues_accessibility'))

    op.drop_table('structureresidues', schema='structure')
    with op.batch_alter_table('compoundtreatments', schema='core') as batch_op:
        batch_op.drop_index(batch_op.f('ix_core_compoundtreatments_probe_id'))
        batch_op.drop_index(batch_op.f('ix_core_compoundtreatments_isreference'))
        batch_op.drop_index(batch_op.f('ix_core_compoundtreatments_compound_id'))

    op.drop_table('compoundtreatments', schema='core')
    with op.batch_alter_table('residuefeatures', schema='chemoproteomics') as batch_op:
        batch_op.drop_index(batch_op.f('ix_chemoproteomics_residuefeatures_source'))
        batch_op.drop_index(batch_op.f('ix_chemoproteomics_residuefeatures_residue_id'))
        batch_op.drop_index(batch_op.f('ix_chemoproteomics_residuefeatures_description'))

    op.drop_table('residuefeatures', schema='chemoproteomics')
    with op.batch_alter_table('list2residue', schema='chemoproteomics') as batch_op:
        batch_op.drop_index(batch_op.f('ix_chemoproteomics_list2residue_residue_id'))

    op.drop_table('list2residue', schema='chemoproteomics')
    op.drop_table('structurechains', schema='structure')
    with op.batch_alter_table('pockets', schema='structure') as batch_op:
        batch_op.drop_index(batch_op.f('ix_structure_pockets_structure_id'))
        batch_op.drop_index(batch_op.f('ix_structure_pockets_pocket_score'))
        batch_op.drop_index(batch_op.f('ix_structure_pockets_drug_score'))

    op.drop_table('pockets', schema='structure')
    with op.batch_alter_table('ligands', schema='structure') as batch_op:
        batch_op.drop_index(batch_op.f('ix_structure_ligands_structure_id'))
        batch_op.drop_index(batch_op.f('ix_structure_ligands_smiles'))
        batch_op.drop_index(batch_op.f('ix_structure_ligands_name'))
        batch_op.drop_index(batch_op.f('ix_structure_ligands_inchi'))
        batch_op.drop_index(batch_op.f('ix_structure_ligands_code'))
        batch_op.drop_index(batch_op.f('ix_structure_ligands_chembl'))
        batch_op.drop_index(batch_op.f('ix_structure_ligands_chain'))

    op.drop_table('ligands', schema='structure')
    op.drop_table('proteinsynonyms', schema='core')
    op.drop_table('plexs', schema='core')
    with op.batch_alter_table('residues', schema='chemoproteomics') as batch_op:
        batch_op.drop_index(batch_op.f('ix_chemoproteomics_residues_uniprot'))
        batch_op.drop_index(batch_op.f('ix_chemoproteomics_residues_type'))

    op.drop_table('residues', schema='chemoproteomics')
    op.drop_table('structures', schema='structure')
    with op.batch_alter_table('proteins', schema='core') as batch_op:
        batch_op.drop_index(batch_op.f('ix_core_proteins_symbol'))

    op.drop_table('proteins', schema='core')
    op.drop_table('experiments', schema='core')
    with op.batch_alter_table('compounds', schema='core') as batch_op:
        batch_op.drop_index(batch_op.f('ix_core_compounds_smiles'))
        batch_op.drop_index(batch_op.f('ix_core_compounds_image'))

    op.drop_table('compounds', schema='core')
    op.drop_table('celltypes', schema='core')
    op.drop_table('residuelists', schema='chemoproteomics')
    op.drop_table('compound_cr_four', schema='chemoproteomics')
    op.drop_table('compound_cr_fifteen', schema='chemoproteomics')
    # ### end Alembic commands ###
