services:

  db:
    image: postgres:13
    restart: always
    env_file:
      - .env
    ports:
      - "6544:5432"
    volumes:
      - db:/var/lib/postgresql/data

  # web:
  #   build: .
  #   restart: always
  #   depends_on:
  #     - db
  #   env_file:
  #     - .env
  #   ports:
  #     - "6969:6969"
  #   volumes:
  #     - .:/app

volumes:
  db: